RNMT-3824 Errors in the first reads/writes of a Key Store when multiple initializations run simultaneously
OutSystems/cordova-plugin-secure-storage pull request #7
Opened 2020-02-11 12:18 UTC by usernuno

## Description
Removes the previous fix.
Improves mutual exclusion in concurrent init calls.

## Context

Fixes https://outsystemsrd.atlassian.net/browse/RNMT-3824

Simultaneous init calls were not being handled correctly. We added proper mutual exclusion and a queue that guarantees only one intent is handled at a time to prevent intent cancellation.

Please review the 2 commits separately for maximum comfort.

## Type of changes

- [ ] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [x] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Components affected
- [x] Android platform
- [ ] iOS platform
- [ ] JavaScript
- [ ] OutSystems

## Tests

Manual tests were performed using Android 9 (uses old intent) and 10 (uses new intent).

## Screenshots (if appropriate)

## Checklist

- [x] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Tests have been created
- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2020-02-11 13:35 UTC, luissilvaos approved these changes

2020-02-11 14:08 UTC, EiyuuZack approved these changes

2020-02-11 14:08 UTC, EiyuuZack commented on src/android/IntentRequest.java
> +    private IntentRequestType type;
Keeping consistency with other classes and the fact there are only getters present, it appears to me these variables could be declared `final`, but I nitpick.

2020-02-11 14:08 UTC, EiyuuZack commented on src/android/SecureStorage.java
> +                    // RSA already has mutual exclusion in all its public methods individually
👍

2020-02-11 17:10 UTC, sandrarodrigues76 requested changes
not a single automatic test?

2020-02-12 11:34 UTC, sandrarodrigues76 approved these changes
The automatic test will be handle soon.

2020-02-12 11:41 UTC, merged